import type { Metadata } from "next";
import { AnalyticsPreference } from "@/components/AnalyticsPreference";
import s from "./privacy.module.css";
export const metadata: Metadata = { title: "Privacy Policy | Chuck Baryames", description: "How Chuck Baryames handles website inquiries, optional analytics and the Cloudflare security check.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <main className={s.page}><div className={s.content}><a className={s.back} href="/">← Chuck Baryames</a><p className={s.date}>Last updated October 4, 2026</p><h1>Privacy Policy</h1><p>This policy explains how I, Chuck Baryames, use information collected through chuckbaryames.com. For questions about your information, email <a href="mailto:chuck@chuckbaryames.com">chuck@chuckbaryames.com</a>.</p>
    <h2>When you contact me</h2><p>The request form collects your name, email, website if supplied, service selection, and message. It also includes limited source labels, such as whether you arrived from LinkedIn, outreach, or a referral. I use this information to reply, review your website, and discuss requested work. A request does not subscribe you to a mailing list.</p><p>The form sends a notification through Resend to my business email. Inquiry information remains in email records so I can handle your request and any resulting project. Please avoid sending passwords, payment-card information, or other sensitive information in the form.</p>
    <h2>Analytics and your choice</h2><p>I use Google Analytics 4 to understand page visits and actions such as service selections, video plays, work-sample links, email-link clicks, and successful requests. Analytics can process browser and device information, approximate location, and an online identifier stored in cookies. Analytics cookies are configured with a 60-day expiry that can renew on a visit.</p><p>I do not send the form’s name, email, website field, or message to Google Analytics. Page URLs sent by this site's analytics code omit query strings and fragments. Advertising personalization and Google Signals are disabled in this site's tag configuration. Preview activity is marked as debug traffic.</p><AnalyticsPreference /><p>Your choice is stored in your browser's local storage until you change it or clear site data. Browser settings and content blockers may also prevent analytics. Read <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google’s Privacy Policy</a> for its processing details.</p>
    <h2>Security and hosting</h2><p>Cloudflare Turnstile checks form requests for spam and abuse. It can process technical information about your device, browser and network connection. This security check is separate from optional analytics. See <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Cloudflare’s Privacy Policy</a>.</p><p>Vercel hosts the website and processes technical request information to deliver it and maintain reliability. Resend processes the notification email. These services may process information outside your state or country.</p>
    <h2>Browser storage</h2><p>Session storage remembers limited campaign labels and your selected service during a browser session. It does not store your message or contact details. Local storage remembers your analytics choice. The form uses a submission identifier to reduce duplicate notifications when a request is retried.</p>
    <h2>Payments and existing orders</h2><p>The main request form does not collect payment. For agreed projects, payments may be handled by Stripe. Existing order flows can store the submitted project brief and order status in Supabase and send transaction-related email. Card information is handled by Stripe, not entered into the request form. See <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">Stripe’s Privacy Policy</a>.</p>
    <h2>Access, correction and deletion</h2><p>Email me if you want to access, correct or request deletion of information you have sent. I may need to confirm that the request comes from you. Some business or payment records may need to be retained for an active project or recordkeeping obligations. I do not sell your contact details or add you to marketing lists through this form.</p>
    <h2>Changes</h2><p>I will update this page when the site's data handling changes. The date above identifies the latest update.</p><a className={s.back} href="/">Return to the website →</a></div></main>;
}
